# Flutter build
variables:
  - group: 'keystore secrets'
  - name : 'projectDirectory'
    value: ''
trigger:
- none
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
        
    - task: DownloadSEcureFile@1
      name: 'Download_keystore_for_app_sign'
      inputs:
        secureFile: 'key.jks'
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: $(Agent.TempDirectory)/key.jks
        apksignerKeystorePassword: $(keypassword)
        apksignerKeystoreAlias: $(key)
        apksignerKeyPassword: $(keypassword)
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)/android'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'
